### ISSUE TITLE
grawlix?

### ISSUE THREAD

**Issue by herohamp** [web-mech/badwords#19]
Can I use grawlix replacements?

**Comment by web-mech** [comment]
I think this is possible. 

The constructor for the word filter accepts `placeHolder` as one of the options. It defaults to `*`.  But what we are doing is simply passing that option to string.replace. 

See
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

Since string.replace can also take a function as the replacement argument, so you could do something like so

```
new Filter({
  placeHolder: function() {
    var grawlix = '#!@$';
    return grawlix[Math.floor(Math.random() * grawlix.length)];
  }
});
```

**Comment by web-mech** [comment]
I'll update the docs to show this possibility
