### ISSUE TITLE
legal words also filtered

### ISSUE THREAD

**Issue by muhammadusmanarshad** [web-mech/badwords#25]
Illegal words filter all words which contain these words. For example: "tit" is a banned word but it also filtered "title"

**Comment by projetedt** [comment]
Same issue here any recommendation or parameter to force strict matching ?

**Comment by nicshackle** [comment]
+ 1

"Hello" gets filtered because it contains "Hell"

**Comment by MussaCharles** [comment]
Same issue here, @muhammadusmanarshad , @projetedt , @nicshackle  did you guys find a way to avoid this to happen?

**Comment by PatNeedham** [comment]
There needs to be some sort of 'exceptions' list

**Comment by PatNeedham** [comment]
The example of 'hello' being filtered because it contains 'hell' is the most glaring false positive in my opinion. One neat site apparently meant for Scrabble but relevant to this issue is Wordfind.com - to find words that 'contain' another word. The example for hello: https://www.wordfind.com/contains/hell/

I'm working on a side project that currently depends on this library, and over the next couple days will gradually build up this type of exceptions list, or probably a dictionary. Because the keys will be strings that appear in the current bad words list, and the values for each key will be the corresponding exceptions (if any exist that is, otherwise there wouldn't be an entry).

**Comment by web-mech** [comment]
Patched with https://github.com/web-mech/badwords/releases/tag/v1.6.2
