### ISSUE TITLE
This does not work on IE , gives syntax error, and shows blank screen on IE.

### ISSUE THREAD

**Issue by chetanbirajdar** [web-mech/badwords#55]
I have created a pipe, using this module .

`import { Pipe, PipeTransform } from '@angular/core';
import * as Filter from 'bad-words';

@Pipe({
    name: 'appProfanityFilter'
})
export class ProfanityFilterPipe implements PipeTransform {
    transform(value: string) {
        if (value === undefined || value === '') {
            return '';
        }
        const filter = new Filter();  
        return filter.clean(value);
    }
}`

And I am using it wherever I want , 
but the issue is, the page does not load on IE. / when I run my code on IE , the browser won't load. After debugging it says that, there is some syntax error. If I comment this pipe , my code works perfect on IE too.

**Comment by web-mech** [comment]
To fix this i'd use a more up to date browser

**Comment by chetanbirajdar** [comment]
> To fix this i'd use a more up to date browser

I wish I could, :(

**Comment by web-mech** [comment]
I'm sorry man. I really have no interest or access to a machine with IE to explore this issue more. If you do figure out the problem, send me a note or even a pull-request with the solution and we'll make it a part of the package.

**Comment by web-mech** [comment]
@chetanbirajdar Maybe you would consider filtering server side instead of in the browser? The list that it pulls down is quite large so that would be sub-optimal in a browser environment anyway. Not to mention you're having to support IE, which even further makes for an overall bad experience. When it comes to IE, try and do as little on the client as possible.
